version: '3.7'
services:
   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:8081"
      volumes:
         - ./frontend:/app
         - /app/node_modules
      environment:
         - REACT_APP_API_URL=$REACT_APP_API_URL
   
   
   mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        hostname: mongodb_host
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: tutorialsDB
            MONGODB_DATA_DIR: /data/db
        ports:
          - "27017:27017"    
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

   api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "admin"
            MONGODB_PASSWORD: "password"
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
volumes:
   mongodbdata:
      driver: local
   appdata:
      driver: local